### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by jasonfan1997** [tansudaylan/tdpy#1]
It show " error : package directory "tdpy" does not exist" when I following the instruction.Why

**Comment by tansudaylan** [comment]
I modified the setup script to avoid potential complaints. It should work now.

**Comment by jasonfan1997** [comment]
It seem I still cannot install it correctly, when I try to import pcat, it still said that no module named tdpy.util.

**Comment by tansudaylan** [comment]
Once you download tdpy and pcat repos, make sure that their paths are in your $PYTHONPATH. setup.py should normally do this, but you can also manually update your $PYTHONPATH to include the relevant folders.
